name: dnd_app_char_sheet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  image_picker: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  isar:
    hosted: https://pub.isar-community.dev
    version: ^3.1.7
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^3.1.7
  permission_handler: ^11.3.1
  file_picker: ^8.0.7
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: ^3.1.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/character.jpg
    - assets/d20.png
    - assets/spells.json